### ISSUE TITLE
[BREAKING CHANGE] Complete conversion from ozone to ozon3

### ISSUE THREAD

**Issue by Milind220** [Ozon3Org/Ozon3#166]
**Conversion of all mentions of ozone to ozon3**

Changing the name of the package to ozon3 entirely will help reduce confusion and inconsistency. As of now the package is called Ozone but is also called ozon3 on PyPI.

* Change every mention of ozone to ozon3

Check the following places:
* Source code files
* Documentation files (.md files in the repository)

**Comment by iamnandhu** [comment]
Hold my beer, I got this
